// Generated by Boronix typegen. Do not edit.

export type BoronixRoute =
  | "/"
  | "/exercises"
  | "/login"
  | "/exercises/[id]"

export type BoronixRouteParams = {
  "/": {}
  "/exercises": {}
  "/login": {}
  "/exercises/[id]": {
    id: string
  }
}

export type RouteParams<T extends BoronixRoute> = BoronixRouteParams[T]

export type PageRoute =
  | "/"
  | "/exercises"
  | "/login"
  | `/exercises/${string}`

export type ApiRoute =
  | "/api/exercises"

export type ActionRoute =
  | "/login?/login"
  | `/exercises/${string}?/submit`
